[versions]
project = "INCLUDED"
# Libraries
binaryCompatibility = "0.18.1"
junit5 = "5.11.3"
clikt = "3.5.4"
antlr-st4 = "4.3.1"
javassist = "3.28.0-GA"
graphql-java = "25.0"
kotlinx = "1.5.2"
kotlinx-metadata = "0.9.0"
kotlin = "1.9.24"

# Plugins
ktlintPluginVersion = "12.1.2"
#noinspection UnusedVersionCatalogEntry
ktlintVersion = "1.4.1"
detekt = "1.23.7"
jacoco = "0.8.12"
dokka = "2.0.0"
gradle-maven-publish = "0.34.0"
develocity = "3.19.2"
foojay-resolver-convention = "1.0.0"
spotbugs = "6.0.26"
idea-gradle-plugin = "1.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPluginVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
#noinspection UnusedVersionCatalogEntry
jacoco = { id = "jacoco", version.ref = "jacoco" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokkaJavaDoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }
develocity = { id = "com.gradle.develocity", version.ref = "develocity" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }

[libraries]
antlr-st4 = { module = "org.antlr:ST4", version.ref = "antlr-st4" }
clikt-jvm = { module = "com.github.ajalt.clikt:clikt-jvm", version.ref = "clikt" }
graphdsl-cli = { module = "io.github.graphdsl:cli", version.ref = "project" }
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadata" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
idea-gradle-plugin = { module = "org.jetbrains.gradle.plugin.idea-ext:org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version.ref = "idea-gradle-plugin" }
kotlinx-binary-compatibility-validator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binaryCompatibility" }
#noinspection UnusedVersionCatalogEntry
junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
#noinspection UnusedVersionCatalogEntry
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
#noinspection UnusedVersionCatalogEntry
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
#noinspection UnusedVersionCatalogEntry
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
#noinspection UnusedVersionCatalogEntry
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
